import { log } from '../core/logger';

/**
 * REST layer for the in-meeting agent (path 2 / TAT — the bot joins as a real
 * participant). All four endpoints authenticate with the app's **tenant** token,
 * which the bridge already holds, so everything runs in-process.
 *
 * None of these are generated by `@larksuiteoapi/node-sdk` (there is no
 * `client.vc.v1.bot.*`), so they go through the client's generic `request()`.
 * Paths and payloads were verified against the live API contract:
 *   POST /open-apis/vc/v1/bots/join     { join_type: 1, join_identify: { meeting_no } }
 *   POST /open-apis/vc/v1/bots/leave    { meeting_id }
 *   POST /open-apis/vc/v1/bots/message  { meeting_id, msg_type, content }
 *   GET  /open-apis/vc/v1/bots/events   ?meeting_id&page_size&page_token
 */

/**
 * The slice of node-sdk's `Client` we need. Declared structurally on purpose:
 * `@larksuiteoapi/node-sdk` is not a direct dependency of the bridge (it is
 * only reachable through `@larksuite/channel`), and taking a second physical
 * copy of it would break identity-carrying request options.
 */
export interface VcRequestClient {
  request<T = unknown>(payload: {
    method: string;
    url: string;
    data?: unknown;
    params?: Record<string, unknown>;
  }): Promise<T>;
}

/** Feishu's response envelope — `request()` resolves to the unwrapped body. */
interface LarkEnvelope<T> {
  code?: number;
  msg?: string;
  data?: T;
}

/** A non-zero `code` from the VC bot API. */
export class VcApiError extends Error {
  constructor(
    readonly code: number,
    message: string,
    readonly endpoint: string,
  ) {
    super(message);
    this.name = 'VcApiError';
  }

  /**
   * `20017` / `ErrNotInGray`: the capability isn't enabled for this app yet
   * (it is an allowlisted beta). Actionable for the operator, so callers
   * surface a dedicated hint instead of a raw API error.
   */
  get notInGray(): boolean {
    return this.code === 20017;
  }
}

const BASE = '/open-apis/vc/v1/bots';

function isRecord(v: unknown): v is Record<string, unknown> {
  return Boolean(v) && typeof v === 'object' && !Array.isArray(v);
}

/**
 * Turn a thrown transport error into a {@link VcApiError} when it carries a
 * Feishu envelope. A non-2xx response rejects inside axios, and the useful part
 * — Feishu's own `code` / `msg` (e.g. "no permission: vc:meeting.message:write")
 * — lives in `response.data`. Without this the caller only ever sees
 * "Request failed with status code 400", which says nothing actionable.
 */
function asVcApiError(err: unknown, endpoint: string): VcApiError | undefined {
  const response = isRecord(err) ? err.response : undefined;
  const data = isRecord(response) ? response.data : undefined;
  if (!isRecord(data)) return undefined;
  const code = typeof data.code === 'number' ? data.code : undefined;
  if (code === undefined) return undefined;
  const msg = typeof data.msg === 'string' && data.msg ? data.msg : `VC API failed with code ${code}`;
  const status = isRecord(response) && typeof response.status === 'number' ? response.status : undefined;
  return new VcApiError(code, status ? `${msg}（HTTP ${status}）` : msg, endpoint);
}

async function call<T>(
  client: VcRequestClient,
  payload: { method: string; url: string; data?: unknown; params?: Record<string, unknown> },
): Promise<T> {
  let res: LarkEnvelope<T>;
  try {
    res = await client.request<LarkEnvelope<T>>(payload);
  } catch (err) {
    throw asVcApiError(err, payload.url) ?? err;
  }
  // A generated method would throw for us; with the generic escape hatch we
  // have to check `code` ourselves.
  const code = res?.code ?? 0;
  if (code !== 0) {
    throw new VcApiError(code, res?.msg ?? `VC API failed with code ${code}`, payload.url);
  }
  return (res?.data ?? {}) as T;
}

/** A meeting number is exactly 9 digits — not a URL and not a long meeting id. */
export function isMeetingNo(value: string): boolean {
  return /^\d{9}$/.test(value.trim());
}

export interface JoinedMeeting {
  /** Long meeting id — required by every subsequent call. */
  meetingId: string;
  meetingNo: string;
  topic?: string;
}

/**
 * Bot joins a meeting by its 9-digit number. Visible to every participant.
 * `join_type` is fixed to 1 by the protocol.
 */
export async function joinMeeting(
  client: VcRequestClient,
  opts: { meetingNo: string; password?: string },
): Promise<JoinedMeeting> {
  const meetingNo = opts.meetingNo.trim();
  if (!isMeetingNo(meetingNo)) {
    throw new Error(`会议号必须是 9 位数字：${opts.meetingNo}`);
  }
  const data = await call<{ meeting?: { id?: string; topic?: string } }>(client, {
    method: 'POST',
    url: `${BASE}/join`,
    data: {
      join_type: 1,
      join_identify: {
        meeting_no: meetingNo,
        ...(opts.password ? { password: opts.password } : {}),
      },
    },
  });
  const meetingId = data.meeting?.id;
  if (!meetingId) throw new Error('入会成功但未返回 meeting.id');
  log.info('meeting', 'joined', { meetingNo, meetingId });
  return { meetingId, meetingNo, ...(data.meeting?.topic ? { topic: data.meeting.topic } : {}) };
}

/** Bot leaves the meeting. Takes the long meeting id, not the 9-digit number. */
export async function leaveMeeting(client: VcRequestClient, meetingId: string): Promise<void> {
  await call(client, { method: 'POST', url: `${BASE}/leave`, data: { meeting_id: meetingId } });
  log.info('meeting', 'left', { meetingId });
}

/** Send an in-meeting chat message (the "弹幕" lane) as the bot. */
export async function sendMeetingText(
  client: VcRequestClient,
  meetingId: string,
  text: string,
): Promise<void> {
  await call(client, {
    method: 'POST',
    url: `${BASE}/message`,
    data: { meeting_id: meetingId, msg_type: 'text', content: text },
  });
}

/** Send an in-meeting reaction (e.g. `LOVE`, `THUMBSUP`, `VC_SoundsClear`). */
export async function sendMeetingReaction(
  client: VcRequestClient,
  meetingId: string,
  emojiType: string,
): Promise<void> {
  await call(client, {
    method: 'POST',
    url: `${BASE}/message`,
    data: { meeting_id: meetingId, msg_type: 'reaction', content: emojiType },
  });
}

/** One raw in-meeting activity record (shape mirrors the push payload's items). */
export interface RawActivityItem {
  event_id?: string;
  meeting?: { id?: string; topic?: string };
  activity_event_type?: string;
  [key: string]: unknown;
}

export interface MeetingEventsPage {
  items: RawActivityItem[];
  /** Cursor for the next incremental pull; absent when caught up. */
  pageToken?: string;
  hasMore: boolean;
}

/**
 * Pull in-meeting events. Primary source for polling mode and the gap-fill
 * path when push drops events. Requires the bot to still be in the meeting.
 */
export async function fetchMeetingEvents(
  client: VcRequestClient,
  opts: { meetingId: string; pageToken?: string; pageSize?: number },
): Promise<MeetingEventsPage> {
  const data = await call<{
    events?: RawActivityItem[];
    meeting_activity_items?: RawActivityItem[];
    page_token?: string;
    has_more?: boolean;
  }>(client, {
    method: 'GET',
    url: `${BASE}/events`,
    // GET bodies are dropped by the client — query args must go in `params`.
    params: {
      meeting_id: opts.meetingId,
      page_size: opts.pageSize ?? 100,
      ...(opts.pageToken ? { page_token: opts.pageToken } : {}),
    },
  });
  // Field name differs across API revisions; accept either.
  const items = data.events ?? data.meeting_activity_items ?? [];
  const pageToken = data.page_token?.trim() ? data.page_token : undefined;
  return {
    items,
    ...(pageToken ? { pageToken } : {}),
    // Keep pulling while the server says so; otherwise hold the cursor.
    hasMore: data.has_more === true,
  };
}
